🐰 Keploy: 2025-06-27T22:56:33+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:56:33+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:57:06+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:57:06+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:58:11+05:30 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2025-06-27T22:58:11+05:30 	[34mINFO[0m	Using the last directory name as appName : book-api-server
🐰 Keploy: 2025-06-27T22:58:11+05:30 	[34mINFO[0m	Generated config file based on the flags that are used
🐰 Keploy: 2025-06-27T22:58:11+05:30 	[31mERROR[0m	failed to get service	{"command": "record", "error": "command not supported in non linux os. if you are on windows or mac, please use the dockerized version of your application"}
🐰 Keploy: 2025-06-27T22:58:11+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-27T22:58:11+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:34:49+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.9"}
🐰 Keploy: 2025-06-28T09:34:49+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:34:50+05:30 	[31mERROR[0m	failed to start keploy in docker	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:34:50+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:34:50+05:30 	[31mERROR[0m	failed to validate flags	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:34:50+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:34:50+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:37:19+05:30 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2025-06-28T09:37:19+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.9"}
🐰 Keploy: 2025-06-28T09:37:19+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:37:20+05:30 	[31mERROR[0m	failed to start keploy in docker	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:37:20+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:37:20+05:30 	[31mERROR[0m	failed to validate flags	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:37:20+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:37:20+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:39:09+05:30 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2025-06-28T09:39:09+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.9"}
🐰 Keploy: 2025-06-28T09:39:10+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T09:39:10+05:30 	[31mERROR[0m	failed to start keploy in docker	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:39:10+05:30 	[31mERROR[0m	failed to run the command in docker	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:39:10+05:30 	[31mERROR[0m	failed to validate flags	{"error": "exit status 125"}
🐰 Keploy: 2025-06-28T09:39:10+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:39:10+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T09:56:08+05:30 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2025-06-28T09:56:08+05:30 	[34mINFO[0m	Starting keploy in docker with image	{"image:": "ghcr.io/keploy/keploy:v2.6.9"}
🐰 Keploy: 2025-06-28T09:56:08+05:30 	[34mINFO[0m	Starting keploy in docker with default context, as that is the current context.
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2025-06-28T04:26:11Z 	[33mWARN[0m	buildDelay is set to 30, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	Using the last directory name as appName : book-api-server
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	failed to write config file	{"error": "open C:\\keploy-data/keploy.yml: no such file or directory"}
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	Generated config file based on the flags that are used
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	keploy requires docker compose containers to be run with external network
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	failed to setup app	{"error": "can't find the docker compose file of user. Are you in the right directory? "}
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	failed setting up the environment	{"error": "can't find the docker compose file of user. Are you in the right directory? "}
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	failed to instrument the application	{"error": "failed setting up the environment"}
🐰 Keploy: 2025-06-28T04:26:11Z 	[34mINFO[0m	stopping Keploy	{"reason": "failed to instrument the application"}
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	failed to record	{"error": "failed to instrument the application"}
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T04:26:11Z 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: permission denied"}
🐰 Keploy: 2025-06-28T09:56:11+05:30 	[34mINFO[0m	exiting the current process as the command is moved to docker
🐰 Keploy: 2025-06-28T10:08:55+05:30 	[31mERROR[0m	No test-sets found. Please record testcases using [90m[keploy record][0m command
🐰 Keploy: 2025-06-28T10:08:55+05:30 	[31mERROR[0m	failed to validate flags	{"error": "No test-sets found. Please record testcases using [90m[keploy record][0m command"}
🐰 Keploy: 2025-06-28T10:08:55+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T10:08:55+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T10:15:16+05:30 	[31mERROR[0m	No test-sets found. Please record testcases using [90m[keploy record][0m command
🐰 Keploy: 2025-06-28T10:15:16+05:30 	[31mERROR[0m	failed to validate flags	{"error": "No test-sets found. Please record testcases using [90m[keploy record][0m command"}
🐰 Keploy: 2025-06-28T10:15:16+05:30 	[31mERROR[0m	Error removing file	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
🐰 Keploy: 2025-06-28T10:15:16+05:30 	[31mERROR[0m	Failed to delete Keploy Logs	{"error": "remove keploy-logs.txt: The process cannot access the file because it is being used by another process."}
